gridding for day 05/02/2018
Traceback (most recent call last):
  File "grid_and_timecollapse_modis.py", line 58, in <module>
    modis_daily=delete_no_overlap(modis_daily)
  File "grid_and_timecollapse_modis.py", line 25, in delete_no_overlap
    dataset = SD(filename, SDC.READ)
  File "/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/pyhdf/SD.py", line 1429, in __init__
    _checkErr('SD', id, "cannot open %s" % path)
  File "/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/pyhdf/error.py", line 23, in _checkErr
    raise HDF4Error(err)
pyhdf.error.HDF4Error: SD (15): File is supported, must be either hdf, cdf, netcdf
WARNING:root:Identified 540 point(s) which were missing values for some or all coordinates - these points have been removed from the data.
WARNING:root:Identified 540 point(s) which were missing values for some or all coordinates - these points have been removed from the data.
/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:101: RuntimeWarning: invalid value encountered in arccos
  90 - rad2deg(arccos(z__/EARTH_RADIUS)),
/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:103: RuntimeWarning: invalid value encountered in arcsin
  (90 - rad2deg(arcsin(sqrt(x__ ** 2 + y__ ** 2)
WARNING:root:Identified 13500 point(s) which were missing values for some or all coordinates - these points have been removed from the data.
WARNING:root:Identified 13500 point(s) which were missing values for some or all coordinates - these points have been removed from the data.
WARNING:root:Identified 13500 point(s) which were missing values for some or all coordinates - these points have been removed from the data.
/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/cis/collocation/data_index.py:79: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  indices = np.vstack(
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Attempted to set invalid unit 'none'.
WARNING:root:Units are not cf compliant, not setting them. Units none
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Attempted to set invalid unit 'none'.
WARNING:root:Units are not cf compliant, not setting them. Units none
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Attempted to set invalid unit 'none'.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
WARNING:root:Standard name 'None' not CF-compliant, this standard name will not be used in the output file.
/home/users/pete_nut/miniconda3/lib/python3.8/site-packages/iris/fileformats/netcdf.py:2122: UserWarning: 'history' is being added as CF data variable attribute, but 'history' should only be a CF global attribute.
  warnings.warn(msg)
gridding for day 05/02/2018
